# Generated by Django 5.2.17 on 2026-10-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=3)),
                ('sprint_number', models.CharField(max_length=2)),
                ('release_date', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
