# Generated by Django 5.2.17 on 2026-10-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=3)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutSprintInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.CharField(max_length=2)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
